// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/jd-opensource/joylive-dashboard/internal/mods"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/rbac"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/rbac/api"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/rbac/biz"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/rbac/dal"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/resource"
	api3 "github.com/jd-opensource/joylive-dashboard/internal/mods/resource/api"
	biz3 "github.com/jd-opensource/joylive-dashboard/internal/mods/resource/biz"
	dal3 "github.com/jd-opensource/joylive-dashboard/internal/mods/resource/dal"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/space"
	api2 "github.com/jd-opensource/joylive-dashboard/internal/mods/space/api"
	biz2 "github.com/jd-opensource/joylive-dashboard/internal/mods/space/biz"
	dal2 "github.com/jd-opensource/joylive-dashboard/internal/mods/space/dal"
	"github.com/jd-opensource/joylive-dashboard/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Cache:           cacher,
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	login := &biz.Login{
		Cache:       cacher,
		Auth:        auther,
		UserDAL:     user,
		UserRoleDAL: userRole,
		MenuDAL:     menu,
		UserBIZ:     bizUser,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	logger := &dal.Logger{
		DB: db,
	}
	bizLogger := &biz.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api.Logger{
		LoggerBIZ: bizLogger,
	}
	casbinx := &rbac.Casbinx{
		Cache:           cacher,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleDAL:         role,
	}
	rbacRBAC := &rbac.RBAC{
		DB:        db,
		MenuAPI:   apiMenu,
		RoleAPI:   apiRole,
		UserAPI:   apiUser,
		LoginAPI:  apiLogin,
		LoggerAPI: apiLogger,
		Casbinx:   casbinx,
	}
	dalSpace := &dal2.Space{
		DB: db,
	}
	bizSpace := &biz2.Space{
		Trans:    trans,
		SpaceDAL: dalSpace,
	}
	apiSpace := &api2.Space{
		SpaceBIZ: bizSpace,
	}
	spaceSpace := &space.Space{
		DB:       db,
		SpaceAPI: apiSpace,
	}
	dalApplication := &dal3.Application{
		DB: db,
	}
	bizApplication := &biz3.Application{
		Trans:         trans,
		ApplicationDAL: dalApplication,
	}
	apiApplication := &api3.Application{
		ApplicationBIZ: bizApplication,
	}
	dalService := &dal3.Service{
		DB: db,
	}
	bizService := &biz3.Service{
		Trans:      trans,
		ServiceDAL: dalService,
	}
	apiService := &api3.Service{
		ServiceBIZ: bizService,
	}
	resourceResource := &resource.Resource{
		DB:             db,
		ApplicationAPI: apiApplication,
		ServiceAPI:     apiService,
	}
	modsMods := &mods.Mods{
		RBAC:     rbacRBAC,
		Resource: resourceResource,
		Space:    spaceSpace,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
