// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/jd-opensource/joylive-dashboard/internal/mods"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/policy"
	api4 "github.com/jd-opensource/joylive-dashboard/internal/mods/policy/api"
	biz4 "github.com/jd-opensource/joylive-dashboard/internal/mods/policy/biz"
	dal4 "github.com/jd-opensource/joylive-dashboard/internal/mods/policy/dal"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/rbac"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/rbac/api"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/rbac/biz"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/rbac/dal"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/resource"
	api2 "github.com/jd-opensource/joylive-dashboard/internal/mods/resource/api"
	biz2 "github.com/jd-opensource/joylive-dashboard/internal/mods/resource/biz"
	dal2 "github.com/jd-opensource/joylive-dashboard/internal/mods/resource/dal"
	"github.com/jd-opensource/joylive-dashboard/internal/mods/space"
	api3 "github.com/jd-opensource/joylive-dashboard/internal/mods/space/api"
	biz3 "github.com/jd-opensource/joylive-dashboard/internal/mods/space/biz"
	dal3 "github.com/jd-opensource/joylive-dashboard/internal/mods/space/dal"
	"github.com/jd-opensource/joylive-dashboard/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Cache:           cacher,
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	login := &biz.Login{
		Cache:       cacher,
		Auth:        auther,
		UserDAL:     user,
		UserRoleDAL: userRole,
		MenuDAL:     menu,
		UserBIZ:     bizUser,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	logger := &dal.Logger{
		DB: db,
	}
	bizLogger := &biz.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api.Logger{
		LoggerBIZ: bizLogger,
	}
	casbinx := &rbac.Casbinx{
		DB:              db,
		Cache:           cacher,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleDAL:         role,
	}
	rbacRBAC := &rbac.RBAC{
		DB:        db,
		MenuAPI:   apiMenu,
		RoleAPI:   apiRole,
		UserAPI:   apiUser,
		LoginAPI:  apiLogin,
		LoggerAPI: apiLogger,
		Casbinx:   casbinx,
	}
	application := &dal2.Application{
		DB: db,
	}
	dataPermission := &dal2.DataPermission{
		DB: db,
	}
	bizDataPermission := &biz2.DataPermission{
		Trans:             trans,
		DataPermissionDAL: dataPermission,
	}
	bizApplication := &biz2.Application{
		Trans:             trans,
		ApplicationDAL:    application,
		DataPermissionBIZ: bizDataPermission,
	}
	apiApplication := &api2.Application{
		ApplicationBIZ: bizApplication,
	}
	service := &dal2.Service{
		DB: db,
	}
	applicationService := &dal2.ApplicationService{
		DB: db,
	}
	bizApplicationService := &biz2.ApplicationService{
		Trans:                 trans,
		ApplicationServiceDAL: applicationService,
		ServiceDAL:            service,
	}
	bizService := &biz2.Service{
		Trans:                 trans,
		ServiceDAL:            service,
		ApplicationServiceBIZ: bizApplicationService,
		DataPermissionBIZ:     bizDataPermission,
	}
	apiService := &api2.Service{
		ServiceBIZ: bizService,
	}
	apiApplicationService := &api2.ApplicationService{
		ApplicationServiceBIZ: bizApplicationService,
	}
	serviceGroup := &dal2.ServiceGroup{
		DB: db,
	}
	bizServiceGroup := &biz2.ServiceGroup{
		Trans:           trans,
		ServiceGroupDAL: serviceGroup,
	}
	apiServiceGroup := &api2.ServiceGroup{
		ServiceGroupBIZ: bizServiceGroup,
	}
	serviceAlias := &dal2.ServiceAlias{
		DB: db,
	}
	bizServiceAlias := &biz2.ServiceAlias{
		Trans:           trans,
		ServiceAliasDAL: serviceAlias,
	}
	apiServiceAlias := &api2.ServiceAlias{
		ServiceAliasBIZ: bizServiceAlias,
	}
	apiDataPermission := &api2.DataPermission{
		DataPermissionBIZ: bizDataPermission,
	}
	resourceResource := &resource.Resource{
		DB:                    db,
		ApplicationAPI:        apiApplication,
		ServiceAPI:            apiService,
		ApplicationServiceAPI: apiApplicationService,
		ServiceGroupAPI:       apiServiceGroup,
		ServiceAliasAPI:       apiServiceAlias,
		DataPermissionAPI:     apiDataPermission,
	}
	dalSpace := &dal3.Space{
		DB: db,
	}
	bizSpace := &biz3.Space{
		Trans:    trans,
		SpaceDAL: dalSpace,
	}
	apiSpace := &api3.Space{
		SpaceBIZ: bizSpace,
	}
	spaceSpace := &space.Space{
		DB:       db,
		SpaceAPI: apiSpace,
	}
	policyLoadbalance := &dal4.PolicyLoadbalance{
		DB: db,
	}
	bizPolicyLoadbalance := &biz4.PolicyLoadbalance{
		Trans:                trans,
		PolicyLoadbalanceDAL: policyLoadbalance,
	}
	apiPolicyLoadbalance := &api4.PolicyLoadbalance{
		PolicyLoadbalanceBIZ: bizPolicyLoadbalance,
	}
	policyRoute := &dal4.PolicyRoute{
		DB: db,
	}
	bizPolicyRoute := &biz4.PolicyRoute{
		Trans:          trans,
		PolicyRouteDAL: policyRoute,
	}
	apiPolicyRoute := &api4.PolicyRoute{
		PolicyRouteBIZ: bizPolicyRoute,
	}
	policyRouteDetail := &dal4.PolicyRouteDetail{
		DB: db,
	}
	bizPolicyRouteDetail := &biz4.PolicyRouteDetail{
		Trans:                trans,
		PolicyRouteDetailDAL: policyRouteDetail,
	}
	apiPolicyRouteDetail := &api4.PolicyRouteDetail{
		PolicyRouteDetailBIZ: bizPolicyRouteDetail,
	}
	policyLimit := &dal4.PolicyLimit{
		DB: db,
	}
	bizPolicyLimit := &biz4.PolicyLimit{
		Trans:          trans,
		PolicyLimitDAL: policyLimit,
	}
	apiPolicyLimit := &api4.PolicyLimit{
		PolicyLimitBIZ: bizPolicyLimit,
	}
	policyCircuitBreak := &dal4.PolicyCircuitBreak{
		DB: db,
	}
	bizPolicyCircuitBreak := &biz4.PolicyCircuitBreak{
		Trans:                 trans,
		PolicyCircuitBreakDAL: policyCircuitBreak,
	}
	apiPolicyCircuitBreak := &api4.PolicyCircuitBreak{
		PolicyCircuitBreakBIZ: bizPolicyCircuitBreak,
	}
	policyPermission := &dal4.PolicyPermission{
		DB: db,
	}
	bizPolicyPermission := &biz4.PolicyPermission{
		Trans:               trans,
		PolicyPermissionDAL: policyPermission,
	}
	apiPolicyPermission := &api4.PolicyPermission{
		PolicyPermissionBIZ: bizPolicyPermission,
	}
	policyAuth := &dal4.PolicyAuth{
		DB: db,
	}
	bizPolicyAuth := &biz4.PolicyAuth{
		Trans:         trans,
		PolicyAuthDAL: policyAuth,
	}
	apiPolicyAuth := &api4.PolicyAuth{
		PolicyAuthBIZ: bizPolicyAuth,
	}
	policyFault := &dal4.PolicyFault{
		DB: db,
	}
	bizPolicyFault := &biz4.PolicyFault{
		Trans:          trans,
		PolicyFaultDAL: policyFault,
	}
	apiPolicyFault := &api4.PolicyFault{
		PolicyFaultBIZ: bizPolicyFault,
	}
	policyInvocation := &dal4.PolicyInvocation{
		DB: db,
	}
	bizPolicyInvocation := &biz4.PolicyInvocation{
		Trans:               trans,
		PolicyInvocationDAL: policyInvocation,
	}
	apiPolicyInvocation := &api4.PolicyInvocation{
		PolicyInvocationBIZ: bizPolicyInvocation,
	}
	policyPolicy := &policy.Policy{
		DB:                    db,
		PolicyLoadbalanceAPI:  apiPolicyLoadbalance,
		PolicyRouteAPI:        apiPolicyRoute,
		PolicyRouteDetailAPI:  apiPolicyRouteDetail,
		PolicyLimitAPI:        apiPolicyLimit,
		PolicyCircuitBreakAPI: apiPolicyCircuitBreak,
		PolicyPermissionAPI:   apiPolicyPermission,
		PolicyAuthAPI:         apiPolicyAuth,
		PolicyFaultAPI:        apiPolicyFault,
		PolicyInvocationAPI:   apiPolicyInvocation,
	}
	modsMods := &mods.Mods{
		RBAC:     rbacRBAC,
		Resource: resourceResource,
		Space:    spaceSpace,
		Policy:   policyPolicy,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
